[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SITE_PASSWORD"

[[edge_functions]]
  path = "/api/login"
  function = "auth"

[[edge_functions]]
  path = "/api/verify"
  function = "verify"

[[edge_functions]]
  path = "/api/logout"
  function = "logout"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

